version: 2.1
jobs: 
  test:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - run:
          command: cd frontend && npm install
      - run:
          command: cd frontend && npm test
workflows:
  tests:
    jobs:
      - test